# Generated by Django 5.1.7 on 2025-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_titie', models.CharField(max_length=30)),
                ('service_dis', models.CharField(max_length=50)),
                ('service_field', models.CharField(max_length=40)),
            ],
        ),
    ]
