# Generated by Django 5.1.7 on 2025-03-31 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='teacher',
        ),
        migrations.AddField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks_obtained',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
